extends "res://tests/khara_boss_check.gd"
## Real arena collisions, locked warnings, complementary dodges, phase cleanup
## and the shared weapon/health-bar contract.
const Hazard = preload("res://scripts/bosses/dhoomketu_hazard.gd")

func reset_dhoomketu() -> void:
	release_inputs()
	change_scene_to_file("res://scenes/bosses/dhoomketu_arena.tscn")
	await scene_changed
	player = current_scene.get_node("Player")
	boss = current_scene.get_node("TestCourse/Boss")
	bar = current_scene.get_node("HUD/BossHealthBar")
	boss.set_physics_process(false)
	await ticks(4)
	player.died.disconnect(current_scene._restart)

func run_checks() -> void:
	await reset_dhoomketu()
	check(boss.health == 28 and bar.boss == boss and bar.visible, "Dhoomketu must bind the shared boss bar at full health")
	check(boss.collision_layer == 4, "All player weapons must reach Dhoomketu on the enemy layer")
	player.position = boss.position + Vector2(-55, 0)
	player.facing_direction = 1
	Input.action_press("attack")
	await ticks(1)
	Input.action_release("attack")
	await ticks(25)
	check(boss.health == 27, "A real lash swing must damage Dhoomketu once")
	player.position = boss.position + Vector2(-200, 0)
	Input.action_press("skyshot")
	await ticks(1)
	Input.action_release("skyshot")
	await ticks(30)
	check(boss.health == 25, "A real skyshot must damage Dhoomketu")
	player.position = boss.position + Vector2(-55, 0)
	Input.action_press("special")
	await ticks(65)
	Input.action_release("special")
	await ticks(3)
	check(boss.health < 25 and bar.health == boss.health, "A charged chakri must damage Dhoomketu and update the bar")
	await reset_dhoomketu()
	boss.start_attack(0, player.position.x)
	var rockets := get_nodes_in_group("dhoomketu_hazards")
	check(rockets.size() == 3, "Phase one must mark three rocket paths")
	check(rockets[0].warning_time < rockets[1].warning_time and rockets[1].warning_time < rockets[2].warning_time, "Rocket launches must be staggered")
	var locked: Vector2 = rockets[0].target_position
	var heading: Vector2 = rockets[0].heading
	await ticks(30)
	check(player.health == 3, "Rockets must not damage during their warning")
	player.position.x = 850
	await ticks(35)
	check(rockets[0].target_position == locked and rockets[0].heading == heading, "Rockets must keep their marked aim when Siya moves")
	await ticks(120)
	check(player.health == 3, "Leaving the marked rocket paths must dodge the salvo")
	await reset_dhoomketu()
	player.set_physics_process(false)
	var rocket: Node2D = boss.spawn_rocket(Vector2(100, 330), player.position + Vector2(0, -20))
	rocket.warning_time = 0.1
	await ticks(35)
	check(player.health == 2, "A diagonal rocket must damage Siya through swept collisions")
	await reset_dhoomketu()
	boss.spawn_hazard(Hazard.Kind.ANAAR, player.position, Vector2(48, 110), 1.25)
	await ticks(110)
	check(player.health == 2, "A burning anaar must deal one damage per player despite its long burn")
	await reset_dhoomketu()
	boss.start_attack(2, player.position.x)
	var fountains := get_nodes_in_group("dhoomketu_hazards")
	check(fountains.size() == 2, "Phase one must place two anaar fountains")
	var mark: Vector2 = fountains[0].position
	await ticks(30)
	player.position.x += 70
	await ticks(95)
	check(player.health == 3 and fountains[0].position == mark, "Anaar marks must lock and leave a walkable escape lane")
	await reset_dhoomketu()
	var wheel: Node2D = boss.spawn_hazard(Hazard.Kind.CHAKRI, player.position + Vector2(-70, 0), Vector2(24, 16), 1.0, 200)
	wheel.warning_time = 0.1
	Input.action_press("jump")
	await ticks(1)
	Input.action_release("jump")
	await ticks(25)
	check(player.health == 3, "A normal jump must clear the ground chakri")
	await reset_dhoomketu()
	wheel = boss.spawn_hazard(Hazard.Kind.CHAKRI, Vector2(60, 430), Vector2(24, 16), 1.0, 200, -1)
	wheel.warning_time = 0.01
	await ticks(8)
	check(wheel.direction == 1 and wheel.bounces_remaining == 0 and wheel.position.x >= 50, "A chakri must bounce once at the deck edge")
	await reset_dhoomketu()
	rocket = boss.spawn_rocket(Vector2(60, 300), Vector2(0, 294))
	rocket.warning_time = 0.01
	await ticks(10)
	check(not is_instance_valid(rocket), "Rockets must stop at solid arena walls")
	await reset_dhoomketu()
	player.facing_direction = 1
	Input.action_press("dash")
	await ticks(1)
	Input.action_release("dash")
	var column: Node2D = boss.spawn_hazard(Hazard.Kind.ANAAR, player.position, Vector2(240, 110), 0.08)
	column.warning_time = 0.01
	await ticks(6)
	check(player.health == 3, "Dash invulnerability must protect against anaar fountains")
	await reset_dhoomketu()
	boss.start_attack(1, player.position.x)
	boss.take_damage(14, Vector2.ZERO)
	await ticks(1)
	check(boss.phase == 2 and boss.state == boss.State.PHASE_SHIFT and bar.phase == 2, "Half health must trigger the all-fuses-lit phase and shared bar")
	check(get_nodes_in_group("dhoomketu_hazards").is_empty(), "Phase transition must clear active hazards")
	boss.start_attack(0, 480)
	check(get_nodes_in_group("dhoomketu_hazards").size() == 4, "Phase two must mark four rocket paths")
	boss._clear_hazards()
	await ticks(1)
	boss.start_attack(1, 480)
	check(get_nodes_in_group("dhoomketu_hazards").size() == 2, "Phase two must release two ground chakris")
	boss._clear_hazards()
	await ticks(1)
	boss.start_attack(2, 480)
	check(get_nodes_in_group("dhoomketu_hazards").size() == 3, "Phase two must mark three anaar lanes")
	boss.take_damage(14, Vector2.ZERO)
	await ticks(1)
	check(boss.state == boss.State.DEAD and boss.collision_layer == 0 and bar.health == 0, "Death must disable the boss and empty its health bar")
	check(get_nodes_in_group("dhoomketu_hazards").is_empty(), "Defeat must clear hazards before campaign victory")
	boss.take_damage(1, Vector2.ZERO)
	check(boss.health == 0, "Dead bosses must ignore further damage")
	await reset_dhoomketu()
	player.set_physics_process(false)
	player.position = Vector2(50, 250)
	boss.set_physics_process(true)
	await ticks(800)
	check(boss.attack_index >= 3, "The live boss must autonomously cycle through all attacks")
	await reset_dhoomketu()
	player.set_physics_process(false)
	player.position = Vector2(50, 250)
	boss.start_attack(2, 480)
	boss.set_physics_process(true)
	await ticks(140)
	check(boss.state == boss.State.RECOVERY and get_nodes_in_group("dhoomketu_hazards").is_empty(), "Fountains must expire before the counterattack recovery window")
	check(boss.state_remaining > 1.0, "Recovery must give Siya time to counterattack")
	print("Dhoomketu checks: %s" % ("PASS" if failures == 0 else "FAIL (%d)" % failures))
	quit(0 if failures == 0 else 1)
